calc_dicts = [
    {'label': 'Revenue TTM',
        'menu_label': 'Revenue TTM',
        'short_label': 'TURTTM',
    },
    {'label': 'Inventory Turnover',
        'menu_label': 'Inventory Turnover',
        'short_label': 'INVTTM',
    },
    {'label': 'Market Cap',
        'menu_label': 'Market Cap',
        'short_label': 'M Cap',
    },
    {'label': 'PE Ratio TTM',
        'menu_label': 'PE Ratio TTM',
        'short_label': 'P/E',
    },
    {'label': 'Enterprise Value',
        'menu_label': 'Enterprise Value',
        'short_label': 'E Val',
    },
    {'label': 'EV / Free Cash Flow TTM',
        'menu_label': 'EV / Free Cash Flow',
        'short_label': 'EV/FCF TTM',
    },
    {'label': 'EV / EBITDA TTM',
        'menu_label': 'EV / EBITDA',
        'short_label': 'EV/EBITDA TTM',
    },
    {'label': 'EV / EBIT TTM',
        'menu_label': 'EV / EBIT',
        'short_label': 'EV/EBIT TTM',
    },
]
